export const quotes = [
	'"Why do I keep touching penisis today" \n- barcode arms',
	'"First you violate my wood" \n- Trump Junior',
	'"All I have gathered from this is that Eminem is Jesus\' grandfather" \n- emo',
	'"I think there\'s like microwaves... On the wall or something" \n- the blacky fat man (definitely my words)',
	'"I left it in Benny" \n- cool beans',
	'"I\'ll add that to my collection of photos of Andrew tied up" \n- cool beans',
	'"I\'M FUCKING ON WATER!" \n- emo',
	'"Right, Mexicans don\'t have elf ears though, do they?" \n- emo',
	'"Time to go grow some women" \n- emo',
	'"SNIFFING TRAINS" \n- cool beans',
	'"How do you get autism from sight?" \n- emo',
	'"I got scars the last time you nailed me" \n- emo',
	'"I am inbred" \n- Ching Chongcentration Camp',
	"\"God doesn't want me to finish, he's clenching my balls, he's clenching my manly fallopian tubes\" \n- stoner",
	'"Yes because the n-word too is a slur for Spanish people" \n- emo',
	'"I didn\'t plan for the sun to be psychic, it just kinda happened" \n- rathew',
	'"Would you rather cheat on a child or on an adult" \n- stoner',
	'"RADIOACTIVE CUM" \n- finnster',
	'"I wanna fuck the manta ray" \n- cool beans',
	'"Just keep your mind on the porn, don\'t cry" \n- the blacky fat man (definitely my words)',
	'"Unless that is your triangular boner, I can see it" \n- morgayna',
	'"So... are you gonna eat your erection or what?" \n- kiddler',
	'"I work at... Milk restaurant" \n- finnster',
	'"Hold on, I need to ask my mum what my funeral plans are" \n- finnster',
	'"I really don\'t want to get these blacks and whites mixed up" \n- the blacky fat man (definitely my words)',
	'"I am the testicle destroyer" \n- RNGesus',
	'"You are dyslexic but talking" \n- robot shagger',
	'"Life is just a glorified quick time event" \n- emo',
	'"Random Jewish noises" \n- rathew',
	'"Jeffery Epstien wishes he was me" \n- finnster',
	'"Could you vacuum seal a child?" \n- the blacky fat man (definitely my words)',
	'"Among us is a thriving minority" \n- finnster',
	'"I think I just made my mother slightly shit herself" \n- emo',
	'"STOP CARESSING YOUR HEAD" \n- robot shagger',
	'"Back in my day we had big chungus" \n- emo',
	'"WHY DO I KEEP GETTING RECOMMENDED VIDEOS ABOUT PANCAKES" \n- emo',
	"\"Dopamine is the lord's cum, and he's busting all over us\" \n- robot shagger",
	'"Bro just felt the bliss of a thousand cums" \n- the blacky fat man (definitely my words)',
	'"I never retard" \n- Ching Chongcentration Camp',
	'"I need you to just send me a clip of your dead sister" \n- emo',
	'"There is a four year old girl in me" \n- the blacky fat man (definitely my words)',
	'"LEO, GIVE ME MY PP BACK" \n- robot shagger',
	'"The cookie has jiggle physics" \n- emo',
	'"My psyduck has down syndrome" \n- emo',
	'"Can I like, cut off one of your heads please?" \n- emo',
	'"Two girls one cut" \n- kobold',
	'"Don\'t quote me on that" \n- cool beans',
	'"Burn out, YAHOOO!" \n- emo',
	'"Speaking of removing legs" \n- the blacky fat man (definitely my words)',
	'"Do it squirt or do it splurt?" \n- stoner',
	'"Boardgaes? Yeah you know what they do when they\'re bored " \n- emo',
	'"Nah just the bloody jellybean, fresh from the woman" \n- emo',
	'"What in the fuck? Why is my donkey flying?" \n- the blacky fat man (definitely my words)',
	'"Those African kids have no idea how hard they have it until they\'ve experienced itchy balls" \n- emo',
	'"What\'s the word for when they drown the kid?" \n- the blacky fat man (definitely my words)',
	'"Just to double check, you know your plant is still in the oven right?" \n- emo',
	'"Gru got nerfed" \n- kobold',
	'"Yea bro, I cum liquid platinum" \n- emo',
	'"Yea man why can\'t Mr Lamont just give birth" \n- emo',
	'"Minority detected" \n- emo',
	'"My favourite starter trio, cyndaquil, totodile and Belgium" \n- emo',
	'"Why are there little children walking in suits" \n- robot shagger',
	'"HE APPROACHES WITH MENACING INTENT!!!" \n- robot shagger',
	'"I\'m going on my femboy arc" \n- emo',
	'"A group of lesbians is called a problem and a group of gays is called a skittle" \n- the blacky fat man (definitely my words)',
	'"Wee Johnny got scammed by Mr beast" \n- finnster',
	"\"I'm going on my villain arc, I'm touching so many kids\" \n- emo",
	'"It\'s six inches long off of memory alone.." \n- robot shagger',
	'"See when, uh..." \n- robot shagger',
	'"Why is there a child in the bin?" \n- robot shagger',
	'"Edible bingus" \n- yap dollar',
	'"I fear for my cock" \n- robot shagger',
	'"He molests me with mischievous intent" \n- robot shagger',
	'"With the power of teen pregnancy" \n- emo',
	'"Spooning the ol\' drawer" \n- kiddler',
	'"Blow me like Al-qaeda" \n- emo',
	'"I\'ve never been so happy to have sheep fuck in front of me" \n- emo',
	'"Miku has super cancer" \n- robot shagger',
	"\"There's people like our bus driver and then there's people like Putin\" \n- robot shagger",
	'"Time to domestically abuse my mother" \n- emo',
	'"No, sonic is Jewish" \n- the blacky fat man (definitely my words)',
	'"I\'m so sorry your feeling bad granny, have some old person juice" \n- baldy fat man',
	'"That woman had more plastic on her face than a Starbucks cup" \n- robot shagger',
	'"I am the one who touches" \n- emo',
	"\"It's got that Pringle texture y'know?\" \n- emo",
	'"I just needed you in the exam hall to whisper sweet fuck all into my ear" \n- emo',
	'"Dad said it\'s my turn to murder the dog" \n- robot shagger',
	'"He isn\'t pregnant but he never fails to deliver" \n- boris123cool',
	'"You either die as a man, or live long enough to see yourself become a femboy" \n- emo',
	'"Do lesbians count as women?" \n- the blacky fat man (definitely my words)',
	'"The hemorrhage button" \n- emo',
	'"With the power of teen pregnancy" \n- emo child',
	'"I\'m Jeff the killer" Jeff the killer as he maliciously Jeff the kills me',
	'"Where\'s the man with half a lung?!" \n- baldy fat man (his words, not mine)',
	'"Dyson hair straighteners, something I don\'t have first-hand experience in" \n- baldy fat man (his words, not mine)',
	'"Oi mate where\'s the shitter? I needa make a deposit" \n- the blacky fat man (definitely my words)',
	'"Shaved monkeys that just got dragged through Top Boss" \n- baldy fat man (his words, not mine)',
	'"Alright munchkins?" \n- baldy fat man (his words, not mine)',
	'"The less out of Lewis, the better" \n- baldy fat man (his words, not mine)',
	'"You\'ve got an 1000 yard stare" \n- baldy fat man (his words, not mine)',
	'"I feel quite sick. I might orally shit in my mouth" \n- the suspicious man',
	'"Directionally up" \n- the blacky fat man (definitely my words)',
	'"Well, you could go with competitors products... Do you have any children? Not for long!" \n- baldy fat man (his words, not mine)',
	'"Ughh god, I gotta read!" \n- emo child',
	'"Oh my god Lewis, your entire bowel is in here!" \n- the womb',
	"\"I'm disgusting? You're the one that left shit rising up the toilet\" \n- the womb",
	'"Have a soda, it\'ll help you see faster" \n- child molester',
	'"*Magestic Music* Princess Diana is coming!" \n- the robber',
	'"Scouse le fuck?" \n- emo child',
	'"It\'s not giving me milk, HATSUNE MIKU?" \n- emo child',
	'"No matter how much you want to lick his feet" \n- baldy fat man (his words, not mine)',
	"\"I'm not saying I'm happy about what happened *cheery smile*\" \n- baldy fat man (his words, not mine)",
	'"There\'s that one saying: Hitler made good motorways... and paintings." \n- baldy fat man (his words, not mine)',
	'"Yonka-core" \n- the blacky fat man (definitely my words)',
	'"Jorkagor" \n- Robot Shagger',
	'"Ah yes, Shallow Swordsman, my favourite metroidcrania" \n- the blacky fat man (definitely my words)',
	'"I get teleportation after cumming?!" \n- the blacky fat man (definitely my words)',
	'"Why are you fucking the equivalent of Tinkerbell?" \n- the blacky fat man (definitely my words)',
	'"Ranked Squirting" \n- Robot Shagger',
	'"She\'s got more plastic in her face than a Starbucks cup." \n- Robot Shagger',
	'"Oh no, my asshole, the dick disintegration chamber" \n- Robot Shagger',
	'"I cheated on my nat 5 english exam higher accounting assignment." \n- Trump Junior',
	'"Oh no, my asshole, the dick disintegration chamber" \n- the fish',
	'"Feel free to bring your youthful photos in! We\'ll make a gallery." \n- old english shhhhh mf',
	'"I\'ll send one of the Amazon drones after you, its like the terminator but next day delivery" \n- Robot Shagger',
	'"Lightly shake Scotland of the face of the Earth" \n- Robot Shagger',
	'"Bribe the dice with handies" \n- child molester',
	'"I hate how the server teases me..." \n- emo child',
	'"Dad says it\'s my turn to murder the dog" \n- Robot shagger',
	'"Car company + Miku = Wine?" \n- Robot shagger',
	'"AI. Artificial Incompetence" \n- Robot shagger',
	"\"I know I'm fat but I don't need 7 sandwiches\" \n- baldy fat man (his words, not mine)",
	'"But I owe Trump Junior (ChatGPT) £100 thousand" \n- baldy fat man (his words, not mine)',
	'"Is this borderline bullying? No? Then I must try harder" \n- baldy fat man (his words, not mine)',
	"\"If it's yellow, let it mellow, if it's brown, flush it down\" \n- the womb",
	'"He isn\'t pregnant but he never fails to deliver" \n- boris123cool (YouTube)',
	'"I\'m outrunning you in a tic tac" \n- ha ha car man',
	'"You look normal to me but you might be a nigger to a colourblind person" \n- robot shagger ',
	'"IT\'S A FUCKING PNG" \n-finnster',
];
